### ISSUE TITLE
nmcl: could not creat nmclient object

### ISSUE THREAD

**Issue by DeastinY** [kootenpv/whereami#13]
[ric@thinkfat ~]$ whereami learn -l esszimmer -n 100
  0%|                                                 | 0/100 [00:00<?, ?it/s]
(process:13373): nmcli-CRITICAL **: Error: Could not create NMClient object: Method "GetAll" with signature "s" on interface "org.freedesktop.DBus.Properties" doesn't exist

Traceback (most recent call last):
  File "/usr/bin/whereami", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/whereami/__main__.py", line 37, in main
    learn(args.location, args.num_samples)
  File "/usr/lib/python3.5/site-packages/whereami/learn.py", line 22, in learn
    new_sample = sample()
  File "/usr/lib/python3.5/site-packages/whereami/get_data.py", line 14, in sample
    aps = wifi_scanner.get_access_points()
  File "/usr/lib/python3.5/site-packages/access_points/__init__.py", line 67, in get_access_points
    results = self.parse_output(out)
  File "/usr/lib/python3.5/site-packages/access_points/__init__.py", line 200, in parse_output
    ssid, bssid, quality, security = split_escaped(line, ':')
ValueError: not enough values to unpack (expected 4, got 1)

**Comment by DeastinY** [comment]
I figured out that (obviously) nmci works with NetworkManager. I masked that :smile: 
Will be looking into alternatives :)

**Comment by DeastinY** [comment]
Opened issue in https://github.com/kootenpv/access_points
