### ISSUE TITLE
Ubuntu:ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by MaDragon** [kootenpv/whereami#19]
Hi,

Newbie here, I run the command "whereami learn -l bedroom -n 100" at first time, it got error as below:

>   0%|                                                   | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/whereami", line 9, in <module>
    load_entry_point('whereami==0.3.50', 'console_scripts', 'whereami')()
  File "/usr/local/lib/python2.7/dist-packages/whereami-0.3.50-py2.7.egg/whereami/__main__.py", line 39, in main
    learn(args.location, args.num_samples)
  File "/usr/local/lib/python2.7/dist-packages/whereami-0.3.50-py2.7.egg/whereami/learn.py", line 22, in learn
    new_sample = sample()
  File "/usr/local/lib/python2.7/dist-packages/whereami-0.3.50-py2.7.egg/whereami/get_data.py", line 15, in sample
    aps = wifi_scanner.get_access_points()
  File "/usr/local/lib/python2.7/dist-packages/access_points/__init__.py", line 77, in get_access_points
    results = self.parse_output(out)
  File "/usr/local/lib/python2.7/dist-packages/access_points/__init__.py", line 210, in parse_output
    ssid, bssid, quality, security = split_escaped(line, ':')
ValueError: need more than 1 value to unpack

What kind of additional argument  I should put in the command?

Thanks

**Comment by kootenpv** [comment]
Thanks for posting an issue. It seems an issue in `access_points`. Are you sure you are connected and there are some wifi access_points available? I hope someone else using ubuntu could verify as I do not have access to a Ubuntu machine (with wifi).

Perhaps another possibility might be to uninstall:

    pip uninstall whereami

and use:

    pip3 install whereami

Does that work for you?

**Comment by MaDragon** [comment]
Hi Kootenpv,

Thanks for your responding.

I have tried in a native ubuntu PC and it worked.

I think the issue was caused by the wifi card in previous PC.

Thanks

**Comment by kootenpv** [comment]
@MaDragon Thanks for narrowing down the problem. Feel free to close the issue if you think there's no way I can help.
