### ISSUE TITLE
windows10,python2.7 error:UTF-16 surrogate

### ISSUE THREAD

**Issue by huanle543** [kootenpv/whereami#21]
C:\Users\weizihan>whereami learn -l bed
  0%|                                                  | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "f:\python2\python2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "f:\python2\python2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\python2\python2\Scripts\whereami.exe\__main__.py", line 9, in <module>
  File "f:\python2\python2\lib\site-packages\whereami\__main__.py", line 39, in main
    learn(args.location, args.num_samples)
  File "f:\python2\python2\lib\site-packages\whereami\learn.py", line 22, in learn
    new_sample = sample()
  File "f:\python2\python2\lib\site-packages\whereami\get_data.py", line 15, in sample
    aps = wifi_scanner.get_access_points()
  File "f:\python2\python2\lib\site-packages\access_points\__init__.py", line 79, in get_access_points
    results = self.parse_output(ensure_str(out))
  File "f:\python2\python2\lib\site-packages\access_points\__init__.py", line 16, in ensure_str
    output = output.decode("utf-16")
  File "f:\python2\python2\lib\encodings\utf_16.py", line 16, in decode
    return codecs.utf_16_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 94-95: illegal UTF-16 surrogate

How to fix this problem?Thanks!

**Comment by kootenpv** [comment]
I think there is a problem with the encoding. Would you have any idea what your encoding might be?

**Comment by huanle543** [comment]
@kootenpv May be utf-8...But in your access_points_init_.py,it first checks utf-8 encoding and then goes to utf-16.So if it is utf-8,the error shouldn't come out.

**Comment by kootenpv** [comment]
I think that the error occurs in the utf16... so that means it is probably another encoding even. Maybe you could show the output of `netsh wlan show networks mode=bssid` on windows
