### ISSUE TITLE
(Py3) missing requirements

### ISSUE THREAD

**Issue by kgadek** [kootenpv/whereami#3]
In a clean environment, the installation did not work. See below (slightly redacted for clarity).

```
❯ pip install whereami
Could not find an activated virtualenv (required).



❯ pyvenv-3.5 tmp/py-master



❯ . ./tmp/py3/bin/activate

(py3) ❯ pip install whereami
Collecting whereami
  Downloading whereami-0.2.21-py2.py3-none-any.whl
Collecting tqdm (from whereami)
  Downloading tqdm-4.8.4-py2.py3-none-any.whl
Collecting access-points (from whereami)
  Downloading access_points-0.0.11-py2.py3-none-any.whl
Collecting scikit-learn (from whereami)
  Downloading scikit_learn-0.17.1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
Installing collected packages: tqdm, access-points, scikit-learn, whereami
Successfully installed access-points-0.0.11 scikit-learn-0.17.1 tqdm-4.8.4 whereami-0.2.21
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.



(py3) ❯ rehash



(py3) ❯ whereami
Traceback (most recent call last):
  File "/Users/konrad/tmp/py3/bin/whereami", line 7, in <module>
    from whereami.__main__ import main
  File "/Users/konrad/tmp/py3/lib/python3.5/site-packages/whereami/__main__.py", line 1, in <module>
    from whereami.predict import predict
  File "/Users/konrad/tmp/py3/lib/python3.5/site-packages/whereami/predict.py", line 3, in <module>
    from whereami.pipeline import get_model
  File "/Users/konrad/tmp/py3/lib/python3.5/site-packages/whereami/pipeline.py", line 2, in <module>
    import numpy as np
ImportError: No module named 'numpy'



(py3) ❯ pip install numpy
Collecting numpy
  Downloading numpy-1.11.1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
Installing collected packages: numpy
Successfully installed numpy-1.11.1
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.



(py3) ❯ whereami
Traceback (most recent call last):
  File "/Users/konrad/tmp/py3/bin/whereami", line 7, in <module>
    from whereami.__main__ import main
  File "/Users/konrad/tmp/py3/lib/python3.5/site-packages/whereami/__main__.py", line 1, in <module>
    from whereami.predict import predict
  File "/Users/konrad/tmp/py3/lib/python3.5/site-packages/whereami/predict.py", line 3, in <module>
    from whereami.pipeline import get_model
  File "/Users/konrad/tmp/py3/lib/python3.5/site-packages/whereami/pipeline.py", line 3, in <module>
    from sklearn.ensemble import RandomForestClassifier
  File "/Users/konrad/tmp/py3/lib/python3.5/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/Users/konrad/tmp/py3/lib/python3.5/site-packages/sklearn/base.py", line 9, in <module>
    from scipy import sparse
ImportError: No module named 'scipy'



(py3) ❯ pip install scipy
Collecting scipy
  Downloading scipy-0.18.1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (21.0MB)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in ./tmp/py3/lib/python3.5/site-packages (from scipy)
Installing collected packages: scipy
Successfully installed scipy-0.18.1
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.



(py3) ❯ whereami
usage: whereami [-h] {predict,predict_proba,crossval,learn} ...

Uses WiFi signals and machine learning to predict where you are.
Feel free to try out commands, if anything is missing it will print help.

You will want to start with `whereami learn`

positional arguments:
  {predict,predict_proba,crossval,learn}

optional arguments:
  -h, --help            show this help message and exit



(py3) ❯ python --version
Python 3.5.2



(py3) ❯ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G1004)
      Kernel Version: Darwin 15.6.0
      (…)
```

**Comment by kootenpv** [comment]
Did it now get solved by the new requirements.txt? Not sure if you can still test :-)

**Comment by kgadek** [comment]
Yes, installed in fresh venv and it Just Works™.

For the record: `whereami==0.2.28`
