### ISSUE TITLE
ValueError: Valid presets for class_weight include "auto" and "subsample". Given "balanced".

### ISSUE THREAD

**Issue by george-cm** [kootenpv/whereami#36]
Hello,

I'm running on Windows 7, Python 3.4.3. I've got a ValueError while trying to learn a location:
```
> whereami learn -l my_desk -n 100
100%|################################################################################################| 100/100 [00:26<00:00,  3.80it/s] Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\whereami.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\whereami\__main__.py", line 45, in main
    learn(args.location, args.num_samples)
  File "c:\python34\lib\site-packages\whereami\learn.py", line 27, in learn
    train_model()
  File "c:\python34\lib\site-packages\whereami\pipeline.py", line 29, in train_model
    lp.fit(X, y)
  File "c:\python34\lib\site-packages\sklearn\pipeline.py", line 141, in fit
    self.steps[-1][-1].fit(Xt, y, **fit_params)
  File "c:\python34\lib\site-packages\sklearn\ensemble\forest.py", line 218, in fit
    y, expanded_class_weight = self._validate_y_class_weight(y)
  File "c:\python34\lib\site-packages\sklearn\ensemble\forest.py", line 417, in _validate_y_class_weight
    % self.class_weight)
ValueError: Valid presets for class_weight include "auto" and "subsample". Given "balanced".
```

This is the first time I'm submitting an issue on Github. Please let me know if I can provide additional information.

Thank you kindly,
George

**Comment by george-cm** [comment]
Nevermind. I updated scikit-learn from 0.16.1 to 0.18.1 and the error went away :)
