### ISSUE TITLE
OSX error

### ISSUE THREAD

**Issue by suhaotian** [kootenpv/whereami#8]
```shell
"This module will be removed in 0.20.", DeprecationWarning)
 21%|████████▊                                 | 21/100 [00:32<02:03,  1.57s/it]
Traceback (most recent call last):
  File "/usr/local/bin/whereami", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/whereami/__main__.py", line 34, in main
    learn(args.location, args.num_samples)
  File "/Library/Python/2.7/site-packages/whereami/learn.py", line 22, in learn
    write_data(label_path, sample())
  File "/Library/Python/2.7/site-packages/whereami/get_data.py", line 14, in sample
    aps = wifi_scanner.get_access_points()
  File "/Library/Python/2.7/site-packages/access_points/__init__.py", line 34, in get_access_points
    results = self.parse_output(out)
  File "/Library/Python/2.7/site-packages/access_points/__init__.py", line 60, in parse_output
    for network in read_plist(output):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 103, in readPlistFromString
    return readPlist(StringIO(data))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1038, column 10

```

**Comment by kootenpv** [comment]
Thanks for posting. This is quite bad.... It seems 20 times went correctly. I'll try to implement 2 parsers, in case one goes wrong. And otherwise skip the sample.

**Comment by kootenpv** [comment]
I rolled it back. Please try it once more, I think there won't be any more errors as of `whereami==0.3.37`

**Comment by suhaotian** [comment]
okay
